<a href="https://colab.research.google.com/github/Saroj-lab/Assessment1/blob/main/Numpy_Pandas_classactivity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#question 1, activity
array = np.arange(10,50)
reshape=array.reshape(4,10)
print(reshape)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [ ]:
#extracting the last column.
last_col = reshape[:,-1]
print(last_col)

[19 29 39 49]


In [ ]:
#Second que
matrix1 = np.full((3,3),5) #to create a 3x3 matrix only with 5
array2 = np.arange(1,10)#creating array from 1 to 9
matrix2 = array2.reshape(3,3) #reshaping it into another matrix.
sum_result = np.add(matrix1, matrix2)
print('the sum is ')
print(sum_result)
prod_result = np.dot(matrix1,matrix2)
print('the product is')
print(prod_result)
sum_transpose = np.transpose(sum_result)
product_transpose = np.transpose(prod_result)
print('the transpose of sum is')
print(sum_transpose)
print('the transpose of product is')
print(product_transpose)


the sum is 
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
the product is
[[60 75 90]
 [60 75 90]
 [60 75 90]]
the transpose of sum is
[[ 6  9 12]
 [ 7 10 13]
 [ 8 11 14]]
the transpose of product is
[[60 60 60]
 [75 75 75]
 [90 90 90]]


In [ ]:

random = np.random.randint(10,101, size=15)
print(random)
#i=1
print(np.where(random>50,-1,random))
print("the number of -1's is",np.sum(random>50))

[37 55 95 20 86 29 49 65 67 32 93 98 63 66 71]
[37 -1 -1 20 -1 29 49 -1 -1 32 -1 -1 -1 -1 -1]
the number of -1's is 10


In [ ]:
arrr = np.random.rand(5*4)
arr_matrix = arrr.reshape(5,4)
print(arr_matrix)
row_sums = np.sum(arr_matrix, axis=1)
max_row_index = np.argmax(row_sums)

print("the row with maximum sum of values is", max_row_index)

print("the normalised matrix is")

for row in arr_matrix:
    for element in row:
        arr_norm = (element - np.min(arr_matrix,axis=1))/(np.max(arr_matrix,axis=1)-np.min(arr_matrix,axis=1))

    print(arr_norm)


[[0.89089012 0.37888081 0.40644492 0.0114368 ]
 [0.18429302 0.64952022 0.04353583 0.90027883]
 [0.64053749 0.12944729 0.36985956 0.70656384]
 [0.44417727 0.86371007 0.66391193 0.15266295]
 [0.28963814 0.14506519 0.07921127 0.26158285]]
the row with maximum sum of values is 3
the normalised matrix is
[ 0.         -0.03746635 -0.20448294 -0.19861714 -0.32208086]
[1.01067561 1.         1.33566009 1.05142945 3.90191408]
[0.79040811 0.7738937  1.         0.77899323 2.98133302]
[0.16058402 0.12737439 0.04022698 0.         0.34906037]
[0.28443357 0.25450691 0.22895818 0.15318239 0.8666744 ]


In [ ]:
arr = np.array([1, 3, 5, 3, 7, 9, 1, 5, 5])
np.unique(arr)
values, counts = np.unique(arr, return_counts=True)
unique_values = values[counts == 1]
print("the unique values are:", unique_values)
duplicate_values = values[counts != 1]
print("the duplcate values are:", duplicate_values)



the unique values are: [7 9]
the duplcate values are: [1 3 5]


In [ ]:
main = np.arange(1,37)
main_matrix = main.reshape(6,6)
print("the central 4x4 matrix is")
central_matrix = main_matrix[1:5,1:5]
print(central_matrix)

print("the even elements are:")

for row in central_matrix:
    for element in row:
      if element%2 == 0:
        print(element)
      else:
        pass


the central 4x4 matrix is
[[ 8  9 10 11]
 [14 15 16 17]
 [20 21 22 23]
 [26 27 28 29]]
the even elements are:
8
10
14
16
20
22
26
28


In [ ]:
first_array = np.arange(0,12)
first_matrix = first_array.reshape(3,4)
reshaped = first_matrix.reshape(2,6)
print("the 2x2 array is\n",reshaped)

flat_reshaped = reshaped.flatten()
print("the flattened version is:\n",flat_reshaped)

second_matrix = flat_reshaped.reshape(4,3)
print("the 4x3 matrix is:\n", second_matrix)



the 2x2 array is
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
the flattened version is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
the 4x3 matrix is:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
a = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])
row_added_array = np.vstack((a,new_row))
print("the row added array is:\n",row_added_array)
new_column = np.array([7,8,9])
column_added_array = np.column_stack((row_added_array, new_column))
print("the column added array is:\n", column_added_array)

the row added array is:
 [[1 2]
 [3 4]
 [5 6]]
the column added array is:
 [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
joint_array = np.concatenate((a,b,c))
print("the joint array is:\n", joint_array)
reshaped_matrix = joint_array.reshape(3,3)
print("the 3x3 reshaped matrix is:\n", reshaped_matrix)
indices=np.argwhere(reshaped_matrix)
print("the diagonal elements are:\n")
for row,col in indices:
  element = reshaped_matrix[row,col]
  if row==col:
    print(element)



the joint array is:
 [1 2 3 4 5 6 7 8 9]
the 3x3 reshaped matrix is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
the diagonal elements are:

1
5
9


In [ ]:
arr_int = np.arange(1,21)
indices = np.argwhere(arr_int)
count=0
for i in indices:
  element = arr_int[i[0]]
  if element%3==0 or element%5==0:
    count=count+1
    print(element)
print("the count is:\n",count)

3
5
6
9
10
12
15
18
20
the count is:
 9


In [1]:
import pandas as pd

In [11]:
from google.colab import drive
data = pd.read_csv("/titanic_dataset (2).csv")
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [12]:
data.head(10)
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C


In [13]:
missing = data.isnull().sum()
missing

,0
PassengerId,0
Survived,0
Pclass,0
Name,0
Sex,0
Age,177
SibSp,0
Parch,0
Ticket,0
Fare,0


In [14]:
survivors = data.groupby('Sex')['Survived'].mean()*100
survivors

,Survived
Sex,
female,74.203822
male,18.890815


In [21]:
Average = data['Age'].mean()
print("the average Age is",Average)
Median = data['Age'].median()
print("the median age is", Median)
SD = data['Age'].std()
print("the standard deviation of age iS", SD)

the average Age is 29.69911764705882
the median age is 28.0
the standard deviation of age iS 14.526497332334044


In [22]:
data.groupby('Pclass')['Name'].count()

,Name
Pclass,
1,216
2,184
3,491


In [23]:
data[(data['Sex'] == 'female') & (data['Age'] < 18) & (data['Survived'] == 1)][['Name']]

,Name
9,"Nasser, Mrs. Nicholas (Adele Achem)"
10,"Sandstrom, Miss. Marguerite Rut"
22,"McGowan, Miss. Anna ""Annie"""
39,"Nicola-Yarred, Miss. Jamila"
43,"Laroche, Miss. Simonne Marie Anne Andree"
58,"West, Miss. Constance Mirium"
68,"Andersson, Miss. Erna Alexandra"
84,"Ilett, Miss. Bertha"
156,"Gilnagh, Miss. Katherine ""Katie"""
172,"Johnson, Miss. Eleanor Ileen"


In [28]:
Median = data['Age'].median()
data['Age'] = data['Age'].fillna(Median)
data['Age']

,Age
0,22.0
1,38.0
2,26.0
3,35.0
4,35.0
...,...
886,27.0
887,19.0
888,28.0
889,26.0


In [33]:
import numpy as np

data['age_group'] = np.where(data['Age'] < 18, 'Child',
                  np.where(data['Age'] <= 60, 'Adult', 'Senior'))
data['age_group']

,age_group
0,Adult
1,Adult
2,Adult
3,Adult
4,Adult
...,...
886,Adult
887,Adult
888,Adult
889,Adult


In [34]:
top_five_fare_payers = data.nlargest(5, 'Fare')
top_five_fare_payers

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Adjusted_Age,age_group
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C,35.0,Adult
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,36.0,Adult
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C,35.0,Adult
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S,19.0,Adult
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S,23.0,Adult


In [38]:
average_fare = data.groupby(['Pclass', 'Sex'])['Fare'].mean()
average_fare

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [43]:
data = data.rename(columns={'Sex': 'gender' , 'Fare':'ticket_fare'})
data

,PassengerId,Survived,Pclass,Name,gender,Age,SibSp,Parch,Ticket,ticket_fare,Cabin,Embarked,Adjusted_Age,age_group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,27.0,Adult
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,19.0,Adult
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,28.0,Adult
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,26.0,Adult


In [51]:
data.groupby('Pclass')['Survived'].value_counts()

Pclass  Survived
1       1           136
        0            80
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

In [50]:
average_age = data.groupby(['Pclass', 'gender'])['Age'].mean()
average_age

Pclass  gender
1       female    33.978723
        male      38.995246
2       female    28.703947
        male      30.512315
3       female    23.572917
        male      26.911873
Name: Age, dtype: float64